#!/bin/bash
# Compose the recorded demo webm into a final mp4 video.
#
# Usage:  bash scripts/compose_demo_video.sh
# Input:  scripts/demo_output/*.webm (generated by record_demo.ts)
# Output: scripts/demo_output/acacia_demo_final.mp4

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/demo_output"

# Find the most recent webm
INPUT=$(ls -t "$OUTPUT_DIR"/*.webm 2>/dev/null | head -1)

if [ -z "$INPUT" ]; then
  echo "Error: No .webm file found in $OUTPUT_DIR"
  echo "Run 'npx tsx scripts/record_demo.ts' first."
  exit 1
fi

OUTPUT="$OUTPUT_DIR/acacia_demo_final.mp4"

echo "Input:  $INPUT"
echo "Output: $OUTPUT"
echo "Encoding..."

ffmpeg -i "$INPUT" \
  -c:v libx264 -preset medium -crf 18 \
  -pix_fmt yuv420p \
  -movflags +faststart \
  -vf "fps=30,scale=1920:1080" \
  -y \
  "$OUTPUT"

echo ""
echo "Done: $OUTPUT"
